[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Categories"
  url = "/categories/"
  weight = 30

[[social]]
  name = "GitHub"
  url = "https://github.com/h-enk"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henkverlinde/"
  weight = 20

[[social]]
  name = "X"
  url = "https://x.com/henkverlinde"
  weight = 30
